# Generated by Django 5.2.1 on 2025-05-29 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DumpingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='reports/')),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(choices=[('Kampala', 'Kampala'), ('Wakiso', 'Wakiso'), ('Masindi', 'Masindi'), ('Kasese', 'Kasese'), ('Iganga', 'Iganga'), ('Bushenyi', 'Bushenyi'), ('Gulu', 'Gulu'), ('Lira', 'Lira'), ('Mbarara', 'Mbarara'), ('Jinja', 'Jinja'), ('Mbale', 'Mbale'), ('Arua', 'Arua'), ('Soroti', 'Soroti'), ('Fort Portal', 'Fort Portal'), ('Hoima', 'Hoima'), ('Masaka', 'Masaka'), ('Mukono', 'Mukono'), ('Nebbi', 'Nebbi'), ('Tororo', 'Tororo'), ('Kabale', 'Kabale'), ('Mityana', 'Mityana'), ('Adjumani', 'Adjumani'), ('Pallisa', 'Pallisa'), ('Kumi', 'Kumi'), ('Bundibugyo', 'Bundibugyo')], default='Kampala', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
