# Generated by Django 5.2.1 on 2025-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastelisting',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=50),
        ),
    ]
