# Generated by Django 5.2.1 on 2025-05-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('waste_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('organic', 'Organic'), ('metal', 'Metal'), ('e-waste', 'E-Waste'), ('clothing', 'Clothing'), ('hazardous', 'Hazardous'), ('construction', 'Construction'), ('medical', 'Medical')], max_length=50)),
                ('category', models.CharField(choices=[('recycling', 'Recycling'), ('composting', 'Composting'), ('disposal', 'Disposal')], max_length=50)),
                ('recycling_process', models.TextField()),
                ('products_made', models.TextField()),
                ('making_process', models.TextField()),
                ('tutorial_link', models.URLField(blank=True, help_text='YouTube link for complex processes', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
