# Generated by Django 5.2.7 on 2025-10-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['waste_type'], 'verbose_name': 'Educational Resource', 'verbose_name_plural': 'Educational Resources'},
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='tutorial_link',
            field=models.URLField(blank=True, help_text='Comma-separated YouTube links for tutorials', max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('waste_type', 'category')},
        ),
    ]
