# Generated by Django 5.2.7 on 2025-10-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_resource_options_resource_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='fun_fact',
            field=models.TextField(blank=True, help_text='Interesting fact about this waste type', null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Resource image', null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='uganda_spotlight',
            field=models.TextField(blank=True, help_text='Uganda-specific success stories or spotlight', null=True),
        ),
    ]
