# Generated by Django 5.2.7 on 2025-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_resource_fun_fact_resource_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resource',
            name='tutorial_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='fun_fact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uganda_spotlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='tutorial_link',
        ),
    ]
