# Generated by Django 5.2.7 on 2025-10-17 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'ordering': ['-date'], 'verbose_name': 'Quiz Score', 'verbose_name_plural': 'Quiz Scores'},
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='total_questions',
            field=models.IntegerField(default=10),
        ),
    ]
