# Generated by Django 5.2.7 on 2025-10-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educ', '0002_alter_quizquestion_options_alter_quizscore_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='wrong_answer_3',
            field=models.CharField(default='Additional option', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='wrong_answer_1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='wrong_answer_2',
            field=models.CharField(max_length=255),
        ),
    ]
